// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType & DisallowNamespaces;
export type BaseLocale = "en";

export type Locales = "en" | "pl";

export type Translation = RootTranslation & DisallowNamespaces;

export type Translations = RootTranslation & {
  home: NamespaceHomeTranslation;
};

type RootTranslation = {
  /**
   * About
   */
  about: string;
  /**
   * Articles
   */
  articles: string;
  /**
   * Contact
   */
  contact: string;
  /**
   * Close menu
   */
  menuClose: string;
  /**
   * Open menu
   */
  menuOpen: string;
  /**
   * News
   */
  news: string;
  /**
   * Projects
   */
  projects: string;
  /**
   * Sign in
   */
  signIn: string;
  /**
   * Sign out
   */
  signOut: string;
  skniKod: {
    /**
     * SKNI KOD
     */
    abbreviation: string;
    /**
     * Student Research Group of Computer Science - "Code"
     */
    name: string;
  };
  theme: {
    /**
     * Dark
     */
    dark: string;
    /**
     * Light
     */
    light: string;
    /**
     * System
     */
    system: string;
  };
};

export type NamespaceHomeTranslation = {
  hero: {
    /**
     * Apps
     */
    apps: string;
    /**
     * Bots
     */
    bots: string;
    /**
     * Code
     */
    code: string;
    /**
     * Student Research Group of Computer Science "Code".
     */
    description: string;
    /**
     * Games
     */
    games: string;
    /**
     * Systems
     */
    systems: string;
    /**
     * Websites
     */
    websites: string;
    /**
     * We create
     */
    weCreate: string;
  };
  /**
   * Join us
   */
  joinUs: string;
};

export type Namespaces = "home";

type DisallowNamespaces = {
  /**
   * reserved for 'home'-namespace\
   * you need to use the `./home/index.ts` file instead
   */
  home?: "[typesafe-i18n] reserved for 'home'-namespace. You need to use the `./home/index.ts` file instead.";
};

export type TranslationFunctions = {
  /**
   * About
   */
  about: () => LocalizedString;
  /**
   * Articles
   */
  articles: () => LocalizedString;
  /**
   * Contact
   */
  contact: () => LocalizedString;
  /**
   * Close menu
   */
  menuClose: () => LocalizedString;
  /**
   * Open menu
   */
  menuOpen: () => LocalizedString;
  /**
   * News
   */
  news: () => LocalizedString;
  /**
   * Projects
   */
  projects: () => LocalizedString;
  /**
   * Sign in
   */
  signIn: () => LocalizedString;
  /**
   * Sign out
   */
  signOut: () => LocalizedString;
  skniKod: {
    /**
     * SKNI KOD
     */
    abbreviation: () => LocalizedString;
    /**
     * Student Research Group of Computer Science - "Code"
     */
    name: () => LocalizedString;
  };
  theme: {
    /**
     * Dark
     */
    dark: () => LocalizedString;
    /**
     * Light
     */
    light: () => LocalizedString;
    /**
     * System
     */
    system: () => LocalizedString;
  };
  home: {
    hero: {
      /**
       * Apps
       */
      apps: () => LocalizedString;
      /**
       * Bots
       */
      bots: () => LocalizedString;
      /**
       * Code
       */
      code: () => LocalizedString;
      /**
       * Student Research Group of Computer Science "Code".
       */
      description: () => LocalizedString;
      /**
       * Games
       */
      games: () => LocalizedString;
      /**
       * Systems
       */
      systems: () => LocalizedString;
      /**
       * Websites
       */
      websites: () => LocalizedString;
      /**
       * We create
       */
      weCreate: () => LocalizedString;
    };
    /**
     * Join us
     */
    joinUs: () => LocalizedString;
  };
};

export type Formatters = {};
