// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType & DisallowNamespaces;
export type BaseLocale = "en";

export type Locales = "en" | "pl";

export type Translation = RootTranslation & DisallowNamespaces;

export type Translations = RootTranslation & {
  home: NamespaceHomeTranslation;
};

type RootTranslation = {
  /**
   * A​b​o​u​t
   */
  about: string;
  /**
   * A​r​t​i​c​l​e​s
   */
  articles: string;
  /**
   * C​o​n​t​a​c​t
   */
  contact: string;
  /**
   * C​l​o​s​e​ ​m​e​n​u
   */
  menuClose: string;
  /**
   * O​p​e​n​ ​m​e​n​u
   */
  menuOpen: string;
  /**
   * N​e​w​s
   */
  news: string;
  /**
   * P​r​o​j​e​c​t​s
   */
  projects: string;
  /**
   * S​i​g​n​ ​i​n
   */
  signIn: string;
  /**
   * S​i​g​n​ ​o​u​t
   */
  signOut: string;
  skniKod: {
    /**
     * S​K​N​I​ ​K​O​D
     */
    abbreviation: string;
    /**
     * S​t​u​d​e​n​t​ ​R​e​s​e​a​r​c​h​ ​G​r​o​u​p​ ​o​f​ ​C​o​m​p​u​t​e​r​ ​S​c​i​e​n​c​e​ ​-​ ​"​C​o​d​e​"
     */
    name: string;
  };
  theme: {
    /**
     * D​a​r​k
     */
    dark: string;
    /**
     * L​i​g​h​t
     */
    light: string;
    /**
     * S​y​s​t​e​m
     */
    system: string;
  };
};

export type NamespaceHomeTranslation = {
  hero: {
    /**
     * A​p​p​s
     */
    apps: string;
    /**
     * B​o​t​s
     */
    bots: string;
    /**
     * C​o​d​e
     */
    code: string;
    /**
     * S​t​u​d​e​n​t​ ​R​e​s​e​a​r​c​h​ ​G​r​o​u​p​ ​o​f​ ​C​o​m​p​u​t​e​r​ ​S​c​i​e​n​c​e​ ​"​C​o​d​e​"​.
     */
    description: string;
    /**
     * G​a​m​e​s
     */
    games: string;
    /**
     * S​y​s​t​e​m​s
     */
    systems: string;
    /**
     * W​e​b​s​i​t​e​s
     */
    websites: string;
    /**
     * W​e​ ​c​r​e​a​t​e
     */
    weCreate: string;
  };
  /**
   * J​o​i​n​ ​u​s
   */
  joinUs: string;
};

export type Namespaces = "home";

type DisallowNamespaces = {
  /**
   * reserved for 'home'-namespace\
   * you need to use the `./home/index.ts` file instead
   */
  home?: "[typesafe-i18n] reserved for 'home'-namespace. You need to use the `./home/index.ts` file instead.";
};

export type TranslationFunctions = {
  /**
   * About
   */
  about: () => LocalizedString;
  /**
   * Articles
   */
  articles: () => LocalizedString;
  /**
   * Contact
   */
  contact: () => LocalizedString;
  /**
   * Close menu
   */
  menuClose: () => LocalizedString;
  /**
   * Open menu
   */
  menuOpen: () => LocalizedString;
  /**
   * News
   */
  news: () => LocalizedString;
  /**
   * Projects
   */
  projects: () => LocalizedString;
  /**
   * Sign in
   */
  signIn: () => LocalizedString;
  /**
   * Sign out
   */
  signOut: () => LocalizedString;
  skniKod: {
    /**
     * SKNI KOD
     */
    abbreviation: () => LocalizedString;
    /**
     * Student Research Group of Computer Science - "Code"
     */
    name: () => LocalizedString;
  };
  theme: {
    /**
     * Dark
     */
    dark: () => LocalizedString;
    /**
     * Light
     */
    light: () => LocalizedString;
    /**
     * System
     */
    system: () => LocalizedString;
  };
  home: {
    hero: {
      /**
       * Apps
       */
      apps: () => LocalizedString;
      /**
       * Bots
       */
      bots: () => LocalizedString;
      /**
       * Code
       */
      code: () => LocalizedString;
      /**
       * Student Research Group of Computer Science "Code".
       */
      description: () => LocalizedString;
      /**
       * Games
       */
      games: () => LocalizedString;
      /**
       * Systems
       */
      systems: () => LocalizedString;
      /**
       * Websites
       */
      websites: () => LocalizedString;
      /**
       * We create
       */
      weCreate: () => LocalizedString;
    };
    /**
     * Join us
     */
    joinUs: () => LocalizedString;
  };
};

export type Formatters = {};
