// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType & DisallowNamespaces;
export type BaseLocale = "en";

export type Locales = "en" | "pl";

export type Translation = RootTranslation & DisallowNamespaces;

export type Translations = RootTranslation & {
  authentication: NamespaceAuthenticationTranslation;
};

type RootTranslation = {
  skniKod: {
    /**
     * S​K​N​I​ ​K​O​D
     */
    abbreviation: string;
    /**
     * S​t​u​d​e​n​t​ ​R​e​s​e​a​r​c​h​ ​G​r​o​u​p​ ​o​f​ ​C​o​m​p​u​t​e​r​ ​S​c​i​e​n​c​e​ ​-​ ​"​C​o​d​e​"
     */
    name: string;
  };
};

export type NamespaceAuthenticationTranslation = {
  /**
   * S​i​g​n​ ​i​n
   */
  signIn: string;
  /**
   * S​i​g​n​ ​o​u​t
   */
  signOut: string;
};

export type Namespaces = "authentication";

type DisallowNamespaces = {
  /**
   * reserved for 'authentication'-namespace\
   * you need to use the `./authentication/index.ts` file instead
   */
  authentication?: "[typesafe-i18n] reserved for 'authentication'-namespace. You need to use the `./authentication/index.ts` file instead.";
};

export type TranslationFunctions = {
  skniKod: {
    /**
     * SKNI KOD
     */
    abbreviation: () => LocalizedString;
    /**
     * Student Research Group of Computer Science - "Code"
     */
    name: () => LocalizedString;
  };
  authentication: {
    /**
     * Sign in
     */
    signIn: () => LocalizedString;
    /**
     * Sign out
     */
    signOut: () => LocalizedString;
  };
};

export type Formatters = {};
